### ISSUE TITLE
Adobe DRM-enabled reading apps for iOS integration

### ISSUE THREAD

**Issue by 22222912** [ThePalaceProject/ios-core#404]
Excuse me  I recently had trouble integrating RMSDK on IOS, can you give me some advice on DRM features?

Adobe provided me with a demo and an sdk zip file, I have successfully run the demo, but I don't know how to properly integrate RMSDK into my project.  I tried to cocopod the entire demo into a pod native library but failed, Also try to create a new static library on the demo and try to put the c++ source files inside, Export for reference But there are still a lot of errors (perhaps configuration and reference path configuration).  And those who have done it should know that the DRM function of the rmsdk needs to be used in conjunction with the certificate.  This allows me to verify whether my above two ideas are correct,

can u  give me  some  advice how to   integrate RMSDK to our project?  Like the packaging  coopod  locla lib or  creating  a. static lid in  RMSDK's demo import  some functional c++ file  to our project?

 
 thx

**Comment by 22222912** [comment]
or XCFramework??

**Comment by jonathangreen** [comment]
Hello @22222912 you can see the reply here to a similar question around Adobe DRM, it might help you out:
https://github.com/ThePalaceProject/android-drm-core/issues/7

I'd like to echo the sentiments in that ticket that if you have any choice at all you should consider an alternative like [LCP](https://readium.org/lcp-specs/) over Adobe DRM.

**Comment by jonathangreen** [comment]
I'm going to close this one out, but feel free to reach out if you have more questions.
